workflows:
  fintunes-test:
    name: Fintunes Test Build
    instance_type: mac_mini_m1  # Valid Mac instance
    max_build_duration: 60
    environment:
      flutter: stable
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
         yarn install --cwd clone
      - name: Build Android
        script: |
          pnpm android --release
      - name: Build iOS
        script: |
          pnpm ios --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.ipa
