workflows:
  fintunes-test:
    name: Fintunes Test Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd $CM_PROJECT_DIR
          # Remove immutable setting temporarily and install
          yarn config set enableImmutableInstalls false
          yarn install
          # Install React Native CLI globally
          npm install -g @react-native-community/cli
      - name: Check project structure
        script: |
          cd $CM_PROJECT_DIR
          echo "Project directory contents:"
          ls -la
          echo "Looking for iOS directory:"
          find . -name "ios" -type d || echo "No ios directory found"
          echo "Looking for Podfile:"
          find . -name "Podfile" || echo "No Podfile found"
      - name: Install iOS dependencies
        script: |
          cd $CM_PROJECT_DIR
          # Check if ios directory exists and has Podfile
          if [ -d "ios" ] && [ -f "ios/Podfile" ]; then
            cd ios
            pod install
          elif [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found, skipping pod install"
          fi
      - name: Build iOS
        script: |
          cd $CM_PROJECT_DIR
          # Use the React Native CLI directly
          npx react-native run-ios --configuration Release
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.ipa
      - ios/build/Build/Products/Release-iphoneos/*.app
      - build/ios/iphoneos/*.ipa
