workflows:
  fintunes-test:
    name: Fintunes Test Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd $CM_PROJECT_DIR
          # Remove immutable setting temporarily and install
          yarn config set enableImmutableInstalls false
          yarn install
      - name: Build Android
        script: |
          cd $CM_PROJECT_DIR
          yarn android --release
      - name: Build iOS
        script: |
          cd $CM_PROJECT_DIR
          yarn ios --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.ipa
